ConnectingChips/ConnectingChips-Front

.gitignore, package-lock.json, package.json, src/App.tsx, src/Component/ConfirmModal.tsx, src/Page/MyPage/MyPage.tsx, src/RouteChangeTracker.ts, src/index.tsx
[구글 애널리틱스 적용하기 2편(react-ga4)](https://whoyoung90.tistory.com/61)
=> 🐴 구글 애널리틱스(GA) 라이브러리 추가 구현

package-lock.json, package.json, src/API/axiosConfig.ts, src/API/joindMinds.ts, src/API/userMind.ts, src/API/userService.ts, src/Page/Home/Home.tsx
axios 기본 설정 및 유저, 작심, 참여한 작심 API
=> ✨ Feat : axios api 추가

src/Page/Home/Home.tsx, src/index.tsx
=> ⚠ Fix : 깃 수리 테스트

src/API/Boards.ts, src/API/axiosConfig.ts, src/API/login.ts, src/API/signup.ts, src/Page/LogIn/LogIn.tsx, src/Page/SignUp/SignUp.tsx, src/Page/UploadPost/UploadPost.tsx
> [!WARNING]  
> 다른 분이 작업한 API 연결이 아직 되어있지 않아서 머지 했을때 에러 발생할 수 있음
* 로그인, 회원가입, 글쓰기 API 구현 및 연결 
* 아이디 중복 여부를 체크하는 함수
https://github.com/khkh0109/ConnectingChips-Front/blob/e9bb69376b4125180bbaae46673bdd731a5c86a2/src/API/signup.ts#L30-L33
* 예외처리 해야함
* 사용자가 이미지 선택하지 않은 상태에서 요청 보내면 500 에러 발생 
* 글 쓰는 도중 토큰 만료되면 토스트 메시지 띄우기
client header에 withCredentials 설정
```ts
client.defaults.headers.common['withCredentials'] = true;
```
=> 로그인, 회원가입, 글쓰기 api 구현 및 연결 

src/Component/GroupCheck.tsx
=> 🔨 Refactor : mindID 이름 변경

src/Component/Mission/GroupHeader.tsx
GroupHeader params -> mindId로 변경
=> GroupHeader params -> mindId로 변경

src/API/Comment.ts, src/API/Mind.ts, src/Component/CTA/CTAContainer.tsx, src/Component/DeleteModal.tsx, src/Component/Mission/GroupArticle.tsx, src/Component/Mission/GroupContent.tsx, src/Component/Mission/GroupHeader.tsx, src/Page/GroupIntro/GroupIntro.tsx, src/Page/GroupPage/Comment.tsx, src/Page/GroupPage/CommentInput.tsx, src/Page/GroupPage/CommentList.tsx, src/Page/GroupPage/GroupPost.tsx, src/Page/GroupPage/GroupPostList.tsx, src/Page/GroupPage/PostContent.tsx, src/Page/GroupPage/PostHeader.tsx, src/Type/Mind.ts, src/data/initialData.ts
groupIntro페이지 진입시 데이터 불러오기
uploadPost페이지 진입시 데이터 불러오기
groupIntro이미지 연결
삭제모달 새로만들어서 연결(삭제하겠습니까?)
re-render 자동으로 되도록 함
=> Article 완성과 rerender 제대로 작동시키기

src/API/Users.ts, src/API/joinedMinds.ts, src/Component/ConfirmModal.tsx, src/Component/OAuthPage.tsx, src/Page/Home/Carresel/ButtonList.tsx, src/Page/Home/GroupList.tsx, src/Page/Home/Home.tsx, src/Page/MyPage/MyPage.tsx, src/data/tocken.ts
⚠ Fix : Home -> MyPage -> Login 구현중
=> ⚠ Fix : Home -> MyPage -> Login 구현중

src/API/Boards.ts, src/API/axiosConfig.ts, src/Page/UploadPost/UploadPost.tsx
* 글쓰기 api 요청 마무리
* 에러 핸들링 
* 현재 에러 발생할 수 있는 곳에 alert로 위치만 표시해둠(현재 주석처리 된 상태)
* 현재는 console로 서버 에러, 토큰 만료 에러를 출력하고 있음 
* postData수정: throw에서 reutnr Promise.reject로 변경함(글쓰기 페이지에서 에러 코드에 접근하려는 목적)
=> 글쓰기 api 마무리, 에러 핸들링

src/API/Boards.ts, src/API/Mind.ts, src/API/Users.ts, src/API/axiosConfig.ts, src/API/joinedMinds.ts, src/App.tsx, src/Component/CTA/CTAContainer.tsx, src/Component/ConfirmModal.tsx, src/Component/GroupCheck.tsx, src/Page/Home/Carresel/ButtonList.tsx, src/Page/Home/GroupList.tsx, src/Page/Home/Home.tsx, src/Page/MyPage/MyPage.tsx, src/Page/MyPage/MyPageMind.tsx, src/Type/Mind.ts, src/data/tocken.ts
=> 홈/로그인/마이페이지 이동간 상태 동기화 & Group Check 인증 추가

src/Component/SignUp/Loginheader.tsx, src/StyleComp/LoginInputS.tsx
* 로그인, 회원가입 input 폰트 사이즈 16 -> 14로 수정 
* 회원가입 헤더 상단에 고정
=> 로그인, 회원가입 스타일 수정 

src/API/Mind.ts, src/API/joinedMinds.ts, src/Component/CTA/CTAContainer.tsx, src/Component/Mission/GroupArticle.tsx, src/Component/Mission/GroupContent.tsx, src/Component/Mission/GroupHeader.tsx, src/Component/Mission/HeadLine.tsx, src/Component/Mission/MissionIntro.tsx, src/Component/Mission/MissionTab.tsx, src/Page/GroupIntro/GroupIntro.tsx, src/Page/GroupPage/Comment.tsx, src/Page/GroupPage/CommentHeader.tsx, src/Page/GroupPage/CommentInput.tsx, src/Page/GroupPage/CommentList.tsx, src/Page/GroupPage/GroupBtn.tsx, src/Page/GroupPage/GroupPage.tsx, src/Page/GroupPage/GroupPostList.tsx, src/Page/GroupPage/PostContent.tsx, src/Page/GroupPage/PostHeader.tsx
=> 🐣 전체적인 스타일조정 및 group 및 groupinput 조정 및 grouppage인증하기 api연결

src/API/Boards.ts, src/API/Mind.ts
=> ⚠ Fix : API 버그 수정

src/Page/UploadPost/UploadPost.tsx
유효하지 않은 토큰(4011)인 경우 
* 로컬스토리지에 있는 토큰 삭제
* 로그인 페이지로 이동
=> 글쓰기 페이지: 유효하지 않은 토큰인 경우 처리 

src/API/Mind.ts, src/API/axiosConfig.ts, src/API/joinedMinds.ts, src/Component/ArticleTab.tsx, src/Component/ConfirmModal.tsx, src/Component/GroupCheck.tsx, src/Hooks/useMission.ts, src/Page/GroupPage/GroupBtn.tsx, src/Page/Home/Carresel/ButtonList.tsx, src/Page/Home/Carresel/ChipList.tsx, src/Page/MyPage/MyPage.tsx, src/Page/MyPage/MyPageMind.tsx, src/Type/Mind.ts
- 전역상태 빼고 props로 복귀
- API문서가 아닌 실제 URL에 맞게 수정
- putRejoin -> postJoin
- ChipList : 0 1 2 3 으로 제한
- isDoneToday가 true인 값을 받을 수 있어 인증하기에 접근을 막음
=> ⚠ Fix : QA 전 FIX

src/Component/GroupCheck.tsx, src/Component/OAuthPage.tsx, src/Page/Home/Carresel/Carresel.tsx
- 인증하기 접근, 회원가입 접근시 홈으로 라우팅
- 나의 작심현황 n일자 -> n일차
=> ⚠ Fix : 라우팅, 오타 수정

src/API/joinedMinds.ts, src/Component/ConfirmModal.tsx, src/Page/Home/Carresel/ButtonList.tsx, src/Page/Home/Carresel/Carresel.tsx, src/Page/Home/GroupList.tsx, src/Page/Home/Home.tsx, src/Page/MyPage/MyPage.tsx, src/Page/MyPage/MyPageMind.tsx, src/Type/Mind.ts
- 메서드에 getToken();  함수 활용
- 전체 작심 리스트에 인원수에 따른 문구 변경 (0명, 1명, n-1명)
- 캐러셀 오타 수정 및 컴포넌트 분리
- 마이페이지 문구 변경 및 스타일 변경
=> 🔨 Refactor : 전체 작심 마이페이지 문구 및 스타일 수정

src/API/Boards.ts, src/API/Comment.ts, src/API/joinedMinds.ts, src/Component/CTA/CTAContainer.tsx, src/Component/Mission/GroupHeader.tsx, src/Page/GroupIntro/GroupIntro.tsx, src/Page/GroupPage/Comment.tsx, src/Page/GroupPage/CommentInput.tsx, src/Page/GroupPage/CommentList.tsx, src/Page/GroupPage/GroupBtn.tsx
그룹인트로에서 참여하기 누르면 세션스토리에 정보저장해서 그룹페이지에서 세션스토리 정보가 있으면 뒤로가기할때 홈으로 가게하기
이전 url가져오는게 다 막히고 안될떄도 있어서 이런식으로 했습니다.
=> 1차 QA 수정사항

src/App.tsx, src/Component/GroupCheck.tsx, src/Page/Home/Carresel/ButtonList.tsx, src/Page/Home/Home.tsx
⚠ Fix : Intro 페이지 GroupCheck / 인증하기 버튼 글자
=> ⚠ Fix : Intro 페이지 GroupCheck / 인증하기 버튼 글자

src/API/Mind.ts, src/Page/GroupIntro/ActiveExample.tsx
작심 별 다른 예시 이미지 적용 
이미지 불러올때 에러가 발생하면 기본 이미지를 보여주도록 설정함
=> 작심 별 다른 예시 이미지 적용

src/App.tsx, src/Page/Home/Carresel/ButtonList.tsx, src/Page/Home/Home.tsx, src/StyleComp/GlobalStyle.tsx, src/StyleComp/LoginInputS.tsx, src/StyleComp/MobileBGS.tsx, src/StyleComp/SignBtnS.tsx, src/index.tsx
https://github.com/ConnectingChips/ConnectingChips-Front/blob/173c014880b1a15491a035fba0b4d28600f75bc0/src/index.tsx#L17-L27
https://github.com/ConnectingChips/ConnectingChips-Front/blob/173c014880b1a15491a035fba0b4d28600f75bc0/src/StyleComp/MobileBGS.tsx#L3-L8
=> 🎨 Style : Home 헤더 여백 설정

src/API/Mind.ts, src/Component/Mission/GroupArticle.tsx, src/Component/Mission/GroupHeader.tsx, src/Page/GroupPage/GroupBtn.tsx, src/Page/Home/Home.tsx
⚠ Fix : 그룹 페이지 버튼 상태 수정
⚠ Fix : 그룹헤더 z-index 30
=> ⚠ Fix : 그룹 페이지 버튼 상태 수정

src/Page/UploadPost/UploadPost.tsx
png, jpg, jpeg 파일 제외 나머지 확장자 선택되면 선택 해제
=> [Fix/image] 이미지 확장자 제한 

src/index.tsx
=> 🗑️ Remove : 쉽표 삭제

src/API/Users.ts, src/API/axiosConfig.ts, src/Component/Toast/ExtensionsBlockMsg.tsx, src/Component/Toast/ImgSizeLimitMsg.tsx, src/Component/Toast/NetworkErrorMsg.tsx, src/Component/Toast/StyledToastContainer.tsx, src/Component/Toast/ToastMsgStyle.ts, src/Page/UploadPost/UploadPost.tsx, src/constant/error.ts
인증하기 페이지 토스트 메시지 추가 
- 네트워크 에러 메시지 
- 파일 확장자 제한 메시지
네트워크 에러 메시지 
파일 확장자 제한 메시지
- 메시지 내용은 임시로 작성(추후 변경 예정)
=> [Feat/toast] 인증하기 페이지 토스트 메시지 추가 

src/API/shareKakao.ts, src/Component/ConfirmModal.tsx, src/Page/MyPage/MyPage.tsx, src/Page/MyPage/MyPageMind.tsx, src/StyleComp/GlobalStyle.tsx
- 헤더 뒤 흰색 배경 적용
- 다시참여하기 2줄 현상 FIX
- 나의 작심현황 폰트 11px
- 카카오 공유하기 이미지 적용
- n일 작심하기 삭제
=> ⚠ Fix : Mypage 수정

src/API/Mind.ts, src/API/joinedMinds.ts, src/App.tsx, src/Component/CTA/CTAContainer.tsx, src/Component/GroupCheck.tsx, src/Component/Mission/GroupArticle.tsx, src/Component/Mission/MissionRule.tsx, src/Component/Mission/MissionTab.tsx, src/Page/GroupIntro/GroupIntro.tsx, src/Page/GroupPage/Comment.tsx, src/Page/GroupPage/GroupPage.tsx, src/Page/GroupPage/GroupPost.tsx, src/Page/GroupPage/GroupPostList.tsx, src/Page/GroupPage/PostContent.tsx, src/StyleComp/GlobalStyle.tsx
글로벌 스타일 대문자제거 (나만씀)
비로그인시 인트로들어가 참가하기 버튼누르면 로그인페이지로
그룹페이지 마진 수정
라벨 폰트사이즈 수정
인증글 수정 보드색 수정
그룹 인트로 배경이미지 깨짐
그룹페이지 사진변경
=> QA 수정사항 4차

src/Component/ConfirmModal.tsx, src/Component/DeleteModal.tsx, src/Page/GroupPage/GroupBtn.tsx, src/Page/MyPage/MyPageMind.tsx
=> 모바일 기본 버튼 컬러 변경 

public/index.html
=> [Feat] GTM 코드 추가

src/Component/ArticleTab.tsx, src/Component/ConfirmModal.tsx, src/Page/Home/Home.tsx, src/Page/MyPage/MyPage.tsx, src/Page/MyPage/MyPageMind.tsx, src/Page/MyPage/MypageBarrel.ts
- ArticleTab의 공용 컴포넌트
https://github.com/ConnectingChips/ConnectingChips-Front/blob/db93fea66da33d1698d74a018b7ab913c1be7bd7/src/Component/ArticleTab.tsx#L3-L26
https://github.com/ConnectingChips/ConnectingChips-Front/blob/db93fea66da33d1698d74a018b7ab913c1be7bd7/src/Page/MyPage/MyPage.tsx#L13-L17
- 반응형 디자인으로 구현
https://github.com/ConnectingChips/ConnectingChips-Front/blob/db93fea66da33d1698d74a018b7ab913c1be7bd7/src/Page/MyPage/MyPage.tsx#L99-L101
- 마이페이지 불필요한 스타일 정리
- import 문 정리
=> 🔨 Refactor : 마이페이지 리팩토링

src/Page/Home/Carresel/Carresel.tsx
https://github.com/ConnectingChips/ConnectingChips-Front/blob/540d4ea95ebdfc1d481150a9b9df781a742aac47/src/Page/Home/Carresel/Carresel.tsx#L25-L41
GTM 작동을 위한 강제 Class주입
=> JSSC-91/GTM/Home

src/API/joinedMinds.ts, src/Page/GroupPage/GroupBtn.tsx, src/Page/Home/Carresel/ButtonList.tsx, src/Page/Home/Carresel/ChipList.tsx, src/Page/Home/Home.tsx, src/Type/Mind.ts
- count와 boardcount로 버튼 구분하던 로직을 keepJoin과 isDoneToday로 변경
- count 3초과하는거 막기
- 홈에서 재작심버튼누르면 업로드페이지로 가는거 그룹페이지로 이동하도록 변경
=> Jssc 89 작심하기, 재작심하기 버튼

src/Component/ConfirmModal.tsx, src/Component/DeleteModal.tsx, src/Page/GroupIntro/GroupIntro.tsx, src/Page/GroupIntro/IntroBarrel.ts, src/Page/GroupPage/GroupPage.tsx, src/Page/GroupPage/PostHeader.tsx
자신의 게시글 하나만 삭제했는데 모든 게시글 삭제되는 버그 고침
게시글 수정버튼 위치 변경
삭제모달 z-index 추가 및 위치조정
=> 게시글 삭제 버그 및 삭제 모달 고침

src/Component/UploadPost/UploadImage.tsx, src/Component/UploadPost/UploadImageTitle.tsx, src/Component/UploadPost/UploadPostHeader.tsx, src/Component/UploadPost/UploadText.tsx, src/Page/UploadPost/UploadPost.tsx, src/StyleComp/UploadWrapperS.tsx
* 필요없는 주석 삭제
* import문, hook 순서 정리
* 10mb 값 상수로 분리
* 컴포넌트 분리
=> [JSSC-67] 인증하기 페이지 1차 리팩토링

src/Component/CTA/CTAContainer.tsx, src/Component/UploadPost/UploadImageTitle.tsx, src/Page/UploadPost/UploadPost.tsx
* 이미지 미 선택 시 버튼 비활성화
* 이미지 미 선택 시 submit 이벤트 실행하지 않음
=> [JSSC-112] 이미지 필수 선택 기능 추가

src/Component/Mission/MissionTab.tsx, src/Page/Home/GroupList.tsx, src/Page/Home/Home.tsx
https://github.com/ConnectingChips/ConnectingChips-Front/blob/3d3c0c3881207be48221005981af747ecc7e28a9/src/Page/Home/Home.tsx#L75-L91
https://github.com/ConnectingChips/ConnectingChips-Front/blob/3d3c0c3881207be48221005981af747ecc7e28a9/src/Page/Home/GroupList.tsx#L26-L34
https://github.com/ConnectingChips/ConnectingChips-Front/blob/3d3c0c3881207be48221005981af747ecc7e28a9/src/Page/Home/GroupList.tsx#L80-L92
https://github.com/ConnectingChips/ConnectingChips-Front/blob/3d3c0c3881207be48221005981af747ecc7e28a9/src/Page/Home/GroupList.tsx#L128-L134
https://github.com/ConnectingChips/ConnectingChips-Front/blob/3d3c0c3881207be48221005981af747ecc7e28a9/src/Component/Mission/MissionTab.tsx#L24-L41
https://github.com/ConnectingChips/ConnectingChips-Front/blob/3d3c0c3881207be48221005981af747ecc7e2 …
=> [JSSC1231] 🎨 Style: 홈 반응형 디자인 (최소 320px 대응)

src/Component/ArticleTab.tsx, src/Page/MyPage/MyPage.tsx, src/Page/MyPage/MyPageMind.tsx, src/Page/MyPage/TermsModal.tsx, src/StyleComp/GlobalStyle.tsx, src/Type/TermsValue.ts
https://github.com/ConnectingChips/ConnectingChips-Front/blob/873327f59b5c7aeb26d588d630ba3880cfabf445/src/Component/ArticleTab.tsx#L30-L39
https://github.com/ConnectingChips/ConnectingChips-Front/blob/873327f59b5c7aeb26d588d630ba3880cfabf445/src/Page/MyPage/MyPage.tsx#L54-L58
::after를 DivideBaS 로 교체
https://github.com/ConnectingChips/ConnectingChips-Front/blob/723d7f2905a5fafa304a9f8b2c301a77abbb2e4c/src/Page/MyPage/MyPage.tsx#L73-L107
https://github.com/ConnectingChips/ConnectingChips-Front/blob/723d7f2905a5fafa304a9f8b2c301a77abbb2e4c/src/Page/MyPage/TermsModal.tsx#L8-L37
https://github.com/ConnectingChips/ConnectingChips-Front/blob/723d7f2905a5fafa304a9f8b2c301a77abbb2e4c/src/Page/MyPage/TermsModal.tsx#L41-L51
`positon : sticky` -> `position : absolute`
=> [JSSC-140] 🎨 Style: 마이페이지 반응형 디자인 (최소 320px) / 이용약관 추가

src/Component/Mission/MissionTab.tsx
MissionSingleS의 outline을 border로 교체
=> [JSSC-140] ⚠ Fix: 전체 작심 현황 보더

src/Page/Home/Home.tsx, src/Page/MyPage/MyPage.tsx
[JSSC-131] 🗑️ Remove: Home 화면 스크롤 코드 삭제
[JSSC-140] 🔨 Refactor: 중복 스타일 클래스 제거
[JSSC-140] ⚠ Fix: 로그아웃 마진값 추가
[JSSC-131]: https://m2jun.atlassian.net/browse/JSSC-131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[JSSC-140]: https://m2jun.atlassian.net/browse/JSSC-140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[JSSC-140]: https://m2jun.atlassian.net/browse/JSSC-140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [JSSC-140] Home 및 마이페이지 스타일 수정

README.md
Docs/readme -> main
프론트엔드 저장소에 프로젝트 설명 추가
- 아래 항목 제외하고 팀 저장소 README와 설명 동일
- 최상단 프론트엔드 저장소 명시
- 아키텍쳐 섹션 삭제
- 테스트 계정 추가
=> README에 전반적인 프로젝트 설명 추가
